export const ALERT = "ALERT";
export const REFETCH_CHATS = "REFETCH_CHATS";

export const NEW_ATTACHMENT = "NEW_ATTACHMENT";
export const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

export const NEW_REQUEST = "NEW_REQUEST";
export const NEW_MESSAGE = "NEW_MESSAGE";

export const START_TYPING = "START_TYPING";
export const STOP_TYPING = "STOP_TYPING";

export const CHAT_JOINED = "CHAT_JOINED";
export const CHAT_LEAVED = "CHAT_LEAVED";

export const ONLINE_USERS = "ONLINE_USERS";
export const ACCEPT_AUDIO_CALL = "ACCEPT_AUDIO_CALL";

export const NEW_AUDIO_CALL_OFFER = "NEW_AUDIO_CALL_OFFER";
export const NEW_AUDIO_CALL_ANSWER = "NEW_AUDIO_CALL_ANSWER";

export const ICE_CANDIDATE = "ICE_CANDIDATE";
export const END_AUDIO_CALL = "END_AUDIO_CALL";